spring.application.name=job

# spring.mongodb.uri=mongodb+srv://akshattiwari9363_db_user:XCyagQG0yg8e1Gf3@job.dats24z.mongodb.net/jobs?retryWrites=true&w=majority&appName=Job

spring.mongodb.uri=mongodb+srv://akshattiwari9363_db_user:XCyagQG0yg8e1Gf3@job.dats24z.mongodb.net/?appName=Job
spring.mongodb.database=jobs